In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import torch

In [2]:
# Load nodes from a Pandas DataFrame
# Example DataFrame with columns X, Y, Z, Atom_Name, Residue_Name, Residue_ID, Atom_Type, and Timeframe
# Load nodes for all timesteps from a .npy file
filepath = 'continuous_edge.csv'  # Replace with the actual file path
df = pd.read_csv(filepath)
df

       Node1  Node2  Edge_Dist  Timeframe
0     N199_2  O2_11   9.867029         30
1     N199_2  O2_11   9.910129         32
2     N199_2  O2_11   9.833108         45
3     N199_2  O2_11   9.881741         53
4     N199_2  O2_11   9.684322         54
...      ...    ...        ...        ...
1868  N563_2   O2_6   9.811772         28
1869  N563_2   O2_6   9.847707         41
1870  N563_2   O2_6   9.869133         42
1871  N563_2   O2_6   9.941175         44
1872  N563_2   O2_6   9.956993         59

[1873 rows x 4 columns]

In [3]:
# Perform one-hot encoding for 'Node1' and 'Node2'
df_encoded = pd.get_dummies(df, columns=['Node1', 'Node2'], drop_first=True)

# Print the encoded DataFrame
df_encoded

,Edge_Dist,Timeframe,Node1_N211_2,Node1_N275_2,Node1_N331_2,Node1_N343_2,Node1_N375_1,Node1_N375_2,Node1_N387_2,Node1_N407_2,...,Node1_N507_2,Node1_N519_2,Node1_N551_1,Node1_N563_1,Node1_N563_2,Node2_O1_11,Node2_O1_6,Node2_O2_10,Node2_O2_11,Node2_O2_6
0,9.867029,30,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,9.910129,32,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,9.833108,45,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,9.881741,53,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,9.684322,54,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1868,9.811772,28,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
1869,9.847707,41,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
1870,9.869133,42,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
1871,9.941175,44,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
1872,9.956993,59,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True

In [4]:
# Extract 'Node1' and 'Node2' columns
nodes_data = df[['Node1', 'Node2']]

# Initialize the OneHotEncoder
encoder = OneHotEncoder(sparse=False, drop='first')

# Fit and transform 'Node1' and 'Node2'
nodes_encoded = encoder.fit_transform(nodes_data)

# Create new column names for the one-hot encoded features
encoded_columns = encoder.get_feature_names_out(['Node1', 'Node2'])

# Replace the original 'Node1' and 'Node2' columns with the one-hot encoded features
df_encoded = pd.concat([df.drop(['Node1', 'Node2'], axis=1), pd.DataFrame(nodes_encoded, columns=encoded_columns)], axis=1)

# Print the encoded DataFrame
df_encoded

/home/mhanowar/Desktop/GNN_repos_server/Virtual_Environment/graphenv/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,Edge_Dist,Timeframe,Node1_N211_2,Node1_N275_2,Node1_N331_2,Node1_N343_2,Node1_N375_1,Node1_N375_2,Node1_N387_2,Node1_N407_2,...,Node1_N507_2,Node1_N519_2,Node1_N551_1,Node1_N563_1,Node1_N563_2,Node2_O1_11,Node2_O1_6,Node2_O2_10,Node2_O2_11,Node2_O2_6
0,9.867029,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,9.910129,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,9.833108,45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,9.881741,53,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,9.684322,54,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1868,9.811772,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1869,9.847707,41,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1870,9.869133,42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1871,9.941175,44,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1872,9.956993,59,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [5]:
# Assuming 'filtered_edge_info' is a DataFrame with 'Edge_Type' column
edge_type = df['Edge_Type'].values.astype(int)

# Edge type features using PyTorch
num_edge_types = len(set(edge_type))
print("Number of Edge Types:", num_edge_types)

# One-hot encode the edge types directly using PyTorch
edge_type_feats = torch.nn.functional.one_hot(torch.from_numpy(edge_type), num_classes=num_edge_types)

# Print the one-hot encoded features and their dimensions
print("One-Hot Encoded Features:")
print(edge_type_feats)
print("Feature Dimensions:", edge_type_feats.size(1))

KeyError: 'Edge_Type'

In [39]:
import pandas as pd
import numpy as np

# Assuming 'df' is your DataFrame
# Numeric feature scaling
numeric_features = ['Edge_Dist']
df[numeric_features] = (df[numeric_features] - df[numeric_features].mean()) / df[numeric_features].std()

# Adding random noise to numeric features
numeric_noise = np.random.normal(0, 0.1, size=(len(df), len(numeric_features)))
df[numeric_features] += np.where(df[numeric_features].applymap(np.isreal), numeric_noise, 0)

# Label smoothing for categorical features (assuming 'Node1' and 'Node2' are categorical)
categorical_features = ['Node1', 'Node2']
df[categorical_features] = df[categorical_features].apply(lambda x: x.apply(lambda y: y + np.random.normal(0, 0.1) if isinstance(y, (int, float)) else y))

# Flipping labels for the target variable
df['Edge_Type'] = 1 - df['Edge_Type']

# Adding random noise to the target variable
df['Edge_Type'] += np.random.choice([-1, 0, 1], size=len(df))
df['Edge_Type'] = df['Edge_Type'].clip(0, 1)  # Ensure values are between 0 and 1

# Print the augmented DataFrame
print(df)

     Time Edge_idx     Node1    Node2  Edge_Dist Edge_Type
0       0        0   n_N11_1  n_N23_1   1.013964         0
1       0        1   n_N11_1  n_N35_1   1.474624         1
2       0        2   n_N11_1  n_N55_1  -2.333547         0
3       0        3   n_N11_1  n_N67_1   0.582845         1
4       0        4   n_N11_1  n_N79_1  -1.242183         0
...   ...      ...       ...      ...        ...       ...
1850    1      928  os_O1_10  o_O2_10  -1.969461         0
1851    1      929  os_O1_11  o_O2_11  -1.800829         1
1852    1      930  os_O1_12  o_O2_12  -1.969332         0
1853    1      931  os_O1_13  o_O2_13  -1.810746         0
1854    1      932  os_O1_14  o_O2_14  -2.062733         0

[1855 rows x 6 columns]

/tmp/ipykernel_2622761/78581602.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[numeric_features] = (df[numeric_features] - df[numeric_features].mean()) / df[numeric_features].std()
/tmp/ipykernel_2622761/78581602.py:11: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[numeric_features] += np.where(df[numeric_features].applymap(np.isreal), numeric_noise, 0)
/tmp/ipykernel_2622761/78581602.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[numeric_features] += np.where(df[numeric_features].applymap(np.isreal), numeric_noise, 0)
/tmp/ipykernel_2622761/78581602.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[categorical_features] = df[categorical_features].apply(lambda x: x.apply(lambda y: y + np.random.normal(0, 0.1) if isinstance(y, (int, float)) else y))
/tmp/ipykernel_2622761/78581602.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Edge_Type'] = 1 - df['Edge_Type']
/tmp/ipykernel_2622761/78581602.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Edge_Type'] += np.random.choice([-1, 0, 1], size=len(df))
/tmp/ipykernel_2622761/78581602.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Edge_Type'] = df['Edge_Type'].clip(0, 1)  # Ensure values are between 0 and 1